name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'api/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  contents: read
  actions: write
  id-token: write

jobs:
  pipeline:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || github.event_name == 'push' && 'dev' || 'pr' }}
    steps:
    - uses: actions/checkout@v3

    - name: Build and Push
      id: build
      uses: actions/github-script@v6
      with:
        script: |
          const startTime = new Date().toISOString();
          console.log(`Starting workflow dispatch at ${startTime}`);
          
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'build-and-push.yml',
            ref: 'main',
            inputs: {
              environment: '${{ github.event_name == 'workflow_dispatch' && inputs.environment || github.event_name == 'push' && 'dev' || 'pr' }}'
            }
          });
          
          console.log('Waiting 5 seconds for workflow to be registered...');
          await new Promise(resolve => setTimeout(resolve, 5000));
          
          const runs = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'build-and-push.yml',
            branch: 'main',
            per_page: 5
          });
          
          const newRun = runs.data.workflow_runs.find(run => new Date(run.created_at) >= new Date(startTime));
          
          if (!newRun) {
            throw new Error('Could not find new workflow run');
          }
          
          core.setOutput('run_id', newRun.id.toString());

    - name: Wait for Build
      uses: ./.github/actions/wait-for-workflow
      with:
        workflow_id: 'build-and-push.yml'
        branch: 'main'
        run_id: ${{ steps.build.outputs.run_id }}

    - name: Deploy API
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      id: deploy
      uses: actions/github-script@v6
      with:
        script: |
          const startTime = new Date().toISOString();
          console.log(`Starting workflow dispatch at ${startTime}`);
          
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'deploy-api.yml',
            ref: 'main',
            inputs: {
              environment: '${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'dev' }}',
              image_tag: '${{ github.sha }}'
            }
          });
          
          console.log('Waiting 5 seconds for workflow to be registered...');
          await new Promise(resolve => setTimeout(resolve, 5000));
          
          const runs = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'deploy-api.yml',
            branch: 'main',
            per_page: 5
          });
          
          const newRun = runs.data.workflow_runs.find(run => new Date(run.created_at) >= new Date(startTime));
          
          if (!newRun) {
            throw new Error('Could not find new workflow run');
          }
          
          core.setOutput('run_id', newRun.id.toString());

    - name: Wait for Deploy
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      uses: ./.github/actions/wait-for-workflow
      with:
        workflow_id: 'deploy-api.yml'
        branch: 'main'
        run_id: ${{ steps.deploy.outputs.run_id }}

    - name: Notify Success
      if: success()
      run: |
        echo "CI/CD pipeline completed successfully!"
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "Image deployed to ${{ inputs.environment }} environment"
        elif [[ "${{ github.event_name }}" == "push" ]]; then
          echo "Image deployed to dev environment"
        fi

    - name: Notify Failure
      if: failure()
      run: |
        echo "CI/CD pipeline failed!" 