name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'api/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  contents: read
  actions: write
  id-token: write

jobs:
  pipeline:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || github.event_name == 'push' && 'dev' || 'pr' }}
    steps:
    - uses: actions/checkout@v3

    - name: Build and Push
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'build-and-push.yml',
            ref: 'main',
            inputs: {
              environment: '${{ github.event_name == 'workflow_dispatch' && inputs.environment || github.event_name == 'push' && 'dev' || 'pr' }}'
            }
          });

    - name: Wait for Build
      uses: ./.github/actions/wait-for-workflow
      with:
        workflow_id: 'build-and-push.yml'
        branch: 'main'

    - name: Deploy API
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'deploy-api.yml',
            ref: 'main',
            inputs: {
              environment: '${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'dev' }}',
              image_tag: '${{ github.sha }}'
            }
          });

    - name: Wait for Deploy
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      uses: ./.github/actions/wait-for-workflow
      with:
        workflow_id: 'deploy-api.yml'
        branch: 'main'

    - name: Notify Success
      if: success()
      run: |
        echo "✅ CI/CD pipeline completed successfully!"
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "Image deployed to ${{ inputs.environment }} environment"
        elif [[ "${{ github.event_name }}" == "push" ]]; then
          echo "Image deployed to dev environment"
        fi

    - name: Notify Failure
      if: failure()
      run: |
        echo "❌ CI/CD pipeline failed!" 